<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Uppu</title>
	<link rel="stylesheet" href="/public/css/main.css">
	<link rel="stylesheet" href="/public/css/file.css">
</head>
<body>
	<header>
		<h1>Uppu</h1>
	</header>
	<div class="fileBlock">
		<div class="img"></div>
		<ul class="fileInfo">
			<li>Название: Изображениеяхпизе павп</li>
			<li>Размер: 12 мб</li>
			<li>Дата загрузки: 12:00 12.02.19</li>
			<li>Комментарий: Загрузил ...</li>
		</ul>
		<a class="uploadButton" href="link.file">Скачать</a>
	</div>
</body>
</html>