{% include "DuplicateItems/header.phtml" %}
    <div class="fileBlock">
        <img src="{{ link }}" alt="">
        <ul class="fileInfo">
            <li>Название: {{ name }}</li>
            {% if size <= 1000 %}
                <li>Размер: {{ size }} Кб.</li>
            {% else %}
                <li>Размер: {{ size / 1000}} Мб.</li>
            {% endif %}
            <li>Дата загрузки: {{ date }}</li>
            <li>Комментарий: {{comment }}</li>
        </ul>
        <a class="uploadButton" href="storage.yandexcloud.net/beta.ardata.public/pro/video/pro5e413d89b75db.mp4" download="video.mp4">Скачать</a>
    </div>
</body>
</html>