<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <title>Uppu</title>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/list.css">
</head>
<body>
    {% include 'DuplicateItems/header.phtml' %}
    {% if filesList %}
        <table>
            <tr>
                <th>Название</th>
                <th>Дата</th>
                <th>Размер</th>
                <th>Скачать</th>
            </tr>
            
                {% for file in filesList %}
                    {% if loop.index % 2 != 0 %}
                        <tr class="trSecond">
                    {% else %}
                        <tr>
                    {% endif %}
                        <td>{{ file.getName }}</td>
                        <td>{{ file.getDate }}</td>
                        {% if file.getSize <= 1000 %}
                            <td>{{ file.getSize }} Кб.</td>
                        {% else %}
                            <td>{{ file.getSize / 1000 }} Мб.</td>
                        {% endif %}
                        <td><a href="/file/{{ file.getNameId }}">Скачать</a></td>
                    </tr>
                {% endfor %}
        </table>
    {% else %}
        <h3>Упс... Файлов нет :(</h3>
    {% endif %}
</body>
</html>