{% extends "DuplicateItems/base.html" %}

{% block head %}
    {{ parent() }}
    <link href="/js/dropzone/dist/dropzone.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript" src="/js/dropzone/dist/dropzone.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script> 
{% endblock %}

{% block content%}
    {% if notify is defined and notify == "emptyName" %}
        <div class="notify">
            Название должно быть заполнено
        </div>        
    {% endif %}
    <form action="/" method="POST" enctype="multipart/form-data" id="myForm" class="uploadForm">
        <input type="text" name="name" id="name" placeholder="Название (не более 30 символов)" maxlength="30">
        <input type="text" name="comment" placeholder="Комментарий (не более 50 символов)" maxlength="50">
        <div class="dropzone" id="myDropzone" name="mainFileUploader">
            <div class="fallback">
                <input name="file" type="file">
                <input type="hidden" name="notjs">
                <button style="display: block;" class="uploadButton" id="uploadButton">Загрузить</button>
            </div>
        </div>
        <input class="deleteButton" type="submit" value="Удалить файл" id="deleteButton">
        <button class="uploadButton" id="uploadButton">Загрузить</button>
    </form>
    <script src="js/forFiles/main.js"></script>
{% endblock %}