<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Uppu</title>
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/file.css">
    <link rel="stylesheet" href="/css/list.css">
    <link href="/js/dropzone/dist/dropzone.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript" src="/js/dropzone/dist/dropzone.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script> 
</head>
<body>
    <header>
        <h1><a href="/">Uppu</a></h1>
        <form class="searchBlock" action="/search" method="GET">
            <input type="text" name="text">
            <input type="submit" value="Искать">
        </form>
        <a href="/list"><h3>Список последних файлов</h3></a>
    </header>