<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Uppu</title>
    <link rel="stylesheet" href="/public/css/main.css">
    <link rel="stylesheet" href="/public/css/file.css">
    <link rel="stylesheet" href="/public/css/list.css">
    <!-- <link rel="stylesheet" href="/src/plugins/dropzone-master/dist/dropzone.css"> -->
    <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
	<!-- <script src="/src/plugins/dropzone-master/dist/dropzone.js"></script> -->
</head>
<body>
    <header>
        <a href="/"><h1>Uppu</h1></a>
        <form class="searchBlock" action="/search" method="GET">
            <input type="text" name="text">
            <input type="submit" name="searchButton" value="Искать">
            <!-- <input type="image" src="public/img/search.png" alt="Ок"> -->
        </form>
        <a href="/list"><h3>Список последних файлов</h3></a>
    </header>