<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Uppu</title>
	<link rel="stylesheet" href="/public/css/main.css">
	<link rel="stylesheet" href="/public/css/list.css">
</head>
<body>
	<header>
		<h1>Uppu</h1>
	</header>
	<table>
		<tr>
			<th>Название</th>
			<th>Дата</th>
			<th>Размер</th>
			<th>Скачать</th>
		</tr>
		<tr class="trSecond">
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>
		<tr>
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>
		<tr class="trSecond">
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>
		<tr>
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>
		<tr class="trSecond">
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>
		<tr>
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>
		<tr class="trSecond">
			<td>Название</td>
			<td>Дата</td>
			<td>Размер</td>
			<td><a href="">Скачать</a></td>
		</tr>


	</table>
</body>
</html>