<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Uppu</title>
	<link rel="stylesheet" href="/public/css/main.css">
</head>
<body>
	<header>
		<h1>Uppu</h1>
	</header>
<!-- 	<form action="">
		<label>
			Выбрать файл
			<input type="file">
		</label>
		<input type="text" placeholder="Название">
		<input type="text" placeholder="Комментарий">
		<input type="submit" value="Загрузить">
	</form> -->

	<label>
		<input type="radio" name="sticker" value="1">
		<img class="stickerBlock" src="/public/img/1.jpg">
	</label>
	<label>
		<input type="radio" name="sticker" value="2">
		<img class="stickerBlock" src="/public/img/2.jpeg">
	</label>
</body>
</html>